use_frameworks!

platform :ios, '8.0'

target 'TYSMKit_Example' do
  pod 'TYSMKit', :path => '../'
#  pod 'TYSMKit'
  
  target 'TYSMKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
